name = "superhome"
main = "app/.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-15"
workers_dev = true
compatibility_flags = ["nodejs_compat"]


[vars]
VITE_PUBLIC_SUPABASE_URL = "https://mksojcqsuapwkgtbbayt.supabase.co"
VITE_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rc29qY3FzdWFwd2tndGJiYXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4OTUxNDIsImV4cCI6MjA3NTQ3MTE0Mn0.P8gu_f3gCEErnmAe4CxdFRDJ854ilYppzlFmmLAT0tk"
SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET = "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"
SUPABASE_AUTH_GOOGLE_CLIENT_ID = "1021894750641-j5nrlhq6fgt108rg7n1019mqfttnatgb.apps.googleusercontent.com"
SUPABASE_AUTH_GOOGLE_SECRET_KEY = "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"


[assets]
directory = "app/.svelte-kit/cloudflare"
binding = "ASSETS"
