name = "superhome-dev"
main = "app/.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-15"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm --prefix app run build"
