name: Deploy Supabase

on:
  push:
    branches:
      # - main
      - dev

jobs:
  deploy:
    # Condition: Only run if '#skip-db' is NOT in the commit message
    if: "!contains(github.event.head_commit.message, '#skip-db')"

    # Map the branch to the corresponding GitHub Environment
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link and Push Migrations
        env:
          # These pull from the Environment selected above
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID: just-to-silence-warning
          SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET_KEY: just-to-silence-warning
        run: |
          supabase link --project-ref "$SUPABASE_PROJECT_ID" -p "$SUPABASE_DB_PASSWORD"
          supabase db push -p "$SUPABASE_DB_PASSWORD"